### ISSUE TITLE
ValueError: reshape() must be passed a nonempty sequence of nonnegative integers.

### ISSUE THREAD

**Issue by YUJX19** [mengyuan-lee/learn-to-branch-d2d#2]
I have a question about why main_total.py has code statements that are non-useful, such as folder creation for"/oracle "and "/val". Was there some code missing during data set generation? 
When I ran main_total.py, I had a problem calling empty data, as follows:
```
generate oracle...
solving problem #1...
Traceback (most recent call last):
  File "G:/matlab_codes/learn-to-branch-d2d-main_Learning to Branch：Accelerating Resource/main_total.py", line 49, in <module>
    main()
  File "G:/matlab_codes/learn-to-branch-d2d-main_Learning to Branch：Accelerating Resource/main_total.py", line 33, in main
    dg.data_generate(mattr,0,num_train)
  File "G:\matlab_codes\learn-to-branch-d2d-main_Learning to Branch：Accelerating Resource\data_generate.py", line 32, in data_generate
    rho, yita_max, label_temp, feature_temp = bb.binaryPro(K,L,R_min_C,P_max_D,P_max_C,h_CD,h_D,h_CB,h_DB,index,mode)
  File "G:\matlab_codes\learn-to-branch-d2d-main_Learning to Branch：Accelerating Resource\bb.py", line 77, in binaryPro
    h_CD.reshape((K0,L0))
ValueError: reshape() must be passed a nonempty sequence of nonnegative integers.

Process finished with exit code 1
```
My version is Matlab R2022b & python 3.8

**Comment by mengyuan-lee** [comment]
Please run "main_generate.m" first.

**Comment by YUJX19** [comment]
I have run your "main_generate.m " in"eng.main_generate(K,L,num_train,'train',nargout=0)" and also generated "data_5_3_train.mat", but I still can't run this code, but I can show you this screenshot,
![image](https://user-images.githubusercontent.com/86273217/210512251-fe13d37c-286e-41ac-a1eb-439090447d26.png)
I ran "python main_total.py" exactly as you instructed on the readme. It's not clear where I went wrong.， Would you be willing to help me overcome this problem?

**Comment by mengyuan-lee** [comment]
Based on the error message, you need check the value of K0, L0, h_CD, and data_5_3_train.mat. Line 77 in bb.py is about data pre-processing. Errors will not exist as long as no errors exist in data.

**Comment by mengyuan-lee** [comment]
The error looks strange. If you can successfully run https://github.com/mengyuan-lee/learn-to-branch-d2d/blob/3aa26c7cdecfb833769c148f8d05684c08da3494/data_generate.py#L26 no errors will happen for https://github.com/mengyuan-lee/learn-to-branch-d2d/blob/3aa26c7cdecfb833769c148f8d05684c08da3494/bb.py#L77 These two lines indicate the same operation.

**Comment by YUJX19** [comment]
As you can see, when processing Line 77 in bb.py, K0, L0, and h_CD all have values, but as you proceed to the following line of code, things start to go wrong.
![image](https://user-images.githubusercontent.com/86273217/210550682-fd92734b-3af4-4d6d-9160-80a80ab58a4e.png)
BTW, the data_5_3_train.mat generated is as follows:
![image](https://user-images.githubusercontent.com/86273217/210551530-a9e43352-c909-43fe-9d8d-01f3eafb9aa6.png)

**Comment by mengyuan-lee** [comment]
The error message indicates that the reshape function fails. But the values of involved variables seem correct. As I mentioned in the previous comment, this is what is expected. Maybe you can search how the reshape function works in python 3.8 and see if there is anything different with that in python 3.6. Note that the type of h_CD is matlab.double. I am not sure whether this type still works for the reshape function in python 3.8.

> The error looks strange. If you can successfully run
> 
> https://github.com/mengyuan-lee/learn-to-branch-d2d/blob/3aa26c7cdecfb833769c148f8d05684c08da3494/data_generate.py#L26
> 
> no errors will happen for
> https://github.com/mengyuan-lee/learn-to-branch-d2d/blob/3aa26c7cdecfb833769c148f8d05684c08da3494/bb.py#L77
> 
> These two lines indicate the same operation.
